#### Prac 7:  Apply Naive Bayes Algorithm on a large dataset and get the accuracy for the same

In [47]:
import numpy as np
import pandas as pd
import math

In [48]:
df = pd.read_csv("Dataset.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [49]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(df, test_size=0.20, random_state=0)

In [50]:
list_of_column_names = []
for row in train:
    list_of_column_names.append(row)

In [51]:
countY=0
countN=0
dataset=np.array(train[list_of_column_names[-1]])
for i in range(len(dataset)):
    if(dataset[i]== 1):
        countY=countY+1
    elif(dataset[i]== 0 ):
        countN=countN+1
print(countY)
print(countN)

221
393

In [52]:
def findProbForUsingFeature(index,feature):
    unique_values=train[feature].unique()
    dataset1=np.array(train[list_of_column_names[index]])
    dataset2=np.array(train[list_of_column_names[-1]])
    computations=[]
    for value in unique_values:
        countYes=0
        countNo=0
        for row in range(len(dataset1)):
            if(dataset1[row]==value and dataset2[row]== 1):
                countYes=countYes+1
            elif(dataset1[row]==value and dataset2[row]== 0):
                countNo=countNo+1
        computations.append([feature,value,countYes,countNo,float(countYes)/float(countY),float(countNo)/float(countN)])
    return computations

In [53]:
computations0 = findProbForUsingFeature(0,list_of_column_names[0])
computations1 = findProbForUsingFeature(1,list_of_column_names[1])
computations2 = findProbForUsingFeature(2,list_of_column_names[2])
computations3 = findProbForUsingFeature(3,list_of_column_names[3])
computations4 = findProbForUsingFeature(4,list_of_column_names[4])
computations5 = findProbForUsingFeature(5,list_of_column_names[5])
computations6 = findProbForUsingFeature(6,list_of_column_names[6])
computations7 = findProbForUsingFeature(7,list_of_column_names[7])

In [54]:
test = test.reset_index()
test

,index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,661,1,199,76,43,0,42.9,1.394,22,1
1,122,2,107,74,30,100,33.6,0.404,23,0
2,113,4,76,62,0,0,34.0,0.391,25,0
3,14,5,166,72,19,175,25.8,0.587,51,1
4,529,0,111,65,0,0,24.6,0.660,31,0
...,...,...,...,...,...,...,...,...,...,...
149,476,2,105,80,45,191,33.7,0.711,29,1
150,482,4,85,58,22,49,27.8,0.306,28,0
151,230,4,142,86,0,0,44.0,0.645,22,1
152,527,3,116,74,15,105,26.3,0.107,24,0
153,380,1,107,72,30,82,30.8,0.821,24,0

In [55]:
final = []
for i in range(len(test)):
    list1 = []
    l1 = test[list_of_column_names[0]][i]
    l2 = test[list_of_column_names[1]][i]
    l3 = test[list_of_column_names[2]][i]
    l4 = test[list_of_column_names[3]][i]
    l5 = test[list_of_column_names[4]][i]
    l6 = test[list_of_column_names[5]][i]
    l7 = test[list_of_column_names[6]][i]
    l8 = test[list_of_column_names[7]][i]
    list1 = [l1,l2,l3,l4,l5,l6,l7,l8]
    final.append(list1)

In [56]:
final

[[1, 199, 76, 43, 0, 42.9, 1.394, 22],
 [2, 107, 74, 30, 100, 33.6, 0.404, 23],
 [4, 76, 62, 0, 0, 34.0, 0.391, 25],
 [5, 166, 72, 19, 175, 25.8, 0.587, 51],
 [0, 111, 65, 0, 0, 24.6, 0.66, 31],
 [1, 81, 72, 18, 40, 26.6, 0.283, 24],
 [9, 152, 78, 34, 171, 34.2, 0.893, 33],
 [3, 176, 86, 27, 156, 33.3, 1.154, 52],
 [2, 127, 58, 24, 275, 27.7, 1.6, 25],
 [6, 103, 72, 32, 190, 37.7, 0.324, 55],
 [3, 158, 76, 36, 245, 31.6, 0.851, 28],
 [5, 187, 76, 27, 207, 43.6, 1.034, 53],
 [5, 114, 74, 0, 0, 24.9, 0.744, 57],
 [2, 82, 52, 22, 115, 28.5, 1.699, 25],
 [8, 65, 72, 23, 0, 32.0, 0.6, 42],
 [0, 108, 68, 20, 0, 27.3, 0.787, 32],
 [8, 179, 72, 42, 130, 32.7, 0.719, 36],
 [1, 73, 50, 10, 0, 23.0, 0.248, 21],
 [4, 132, 86, 31, 0, 28.0, 0.419, 63],
 [5, 99, 54, 28, 83, 34.0, 0.499, 30],
 [4, 144, 82, 32, 0, 38.5, 0.554, 37],
 [2, 118, 80, 0, 0, 42.9, 0.693, 21],
 [2, 87, 0, 23, 0, 28.9, 0.773, 25],
 [3, 61, 82, 28, 0, 34.4, 0.243, 46],
 [1, 97, 66, 15, 140, 23.2, 0.487, 22],
 [1, 124, 60, 32, 0, 35.8, 0.514, 21],
 [0, 104, 76, 0, 0, 18.4, 0.582, 27],
 [13, 153, 88, 37, 140, 40.6, 1.174, 39],
 [2, 112, 66, 22, 0, 25.0, 0.307, 24],
 [5, 110, 68, 0, 0, 26.0, 0.292, 30],
 [7, 136, 74, 26, 135, 26.0, 0.647, 51],
 [0, 102, 64, 46, 78, 40.6, 0.496, 21],
 [0, 102, 86, 17, 105, 29.3, 0.695, 27],
 [2, 122, 52, 43, 158, 36.2, 0.816, 28],
 [1, 119, 54, 13, 50, 22.3, 0.205, 24],
 [5, 168, 64, 0, 0, 32.9, 0.135, 41],
 [11, 136, 84, 35, 130, 28.3, 0.26, 42],
 [2, 117, 90, 19, 71, 25.2, 0.313, 21],
 [1, 119, 44, 47, 63, 35.5, 0.28, 25],
 [3, 180, 64, 25, 70, 34.0, 0.271, 26],
 [0, 119, 64, 18, 92, 34.9, 0.725, 23],
 [3, 90, 78, 0, 0, 42.7, 0.559, 21],
 [6, 99, 60, 19, 54, 26.9, 0.497, 32],
 [3, 193, 70, 31, 0, 34.9, 0.241, 25],
 [2, 197, 70, 45, 543, 30.5, 0.158, 53],
 [0, 102, 75, 23, 0, 0.0, 0.572, 21],
 [2, 108, 62, 32, 56, 25.2, 0.128, 21],
 [3, 129, 64, 29, 115, 26.4, 0.219, 28],
 [4, 109, 64, 44, 99, 34.8, 0.905, 26],
 [4, 125, 80, 0, 0, 32.3, 0.536, 27],
 [10, 133, 68, 0, 0, 27.0, 0.245, 36],
 [2, 108, 52, 26, 63, 32.5, 0.318, 22],
 [12, 151, 70, 40, 271, 41.8, 0.742, 38],
 [7, 137, 90, 41, 0, 32.0, 0.391, 39],
 [0, 91, 68, 32, 210, 39.9, 0.381, 25],
 [1, 0, 48, 20, 0, 24.7, 0.14, 22],
 [1, 85, 66, 29, 0, 26.6, 0.351, 31],
 [5, 115, 98, 0, 0, 52.9, 0.209, 28],
 [2, 134, 70, 0, 0, 28.9, 0.542, 23],
 [10, 115, 0, 0, 0, 0.0, 0.261, 30],
 [8, 167, 106, 46, 231, 37.6, 0.165, 43],
 [4, 147, 74, 25, 293, 34.9, 0.385, 30],
 [0, 125, 68, 0, 0, 24.7, 0.206, 21],
 [0, 138, 0, 0, 0, 36.3, 0.933, 25],
 [3, 182, 74, 0, 0, 30.5, 0.345, 29],
 [8, 197, 74, 0, 0, 25.9, 1.191, 39],
 [9, 165, 88, 0, 0, 30.4, 0.302, 49],
 [3, 122, 78, 0, 0, 23.0, 0.254, 40],
 [9, 106, 52, 0, 0, 31.2, 0.38, 42],
 [9, 72, 78, 25, 0, 31.6, 0.28, 38],
 [2, 108, 64, 0, 0, 30.8, 0.158, 21],
 [7, 119, 0, 0, 0, 25.2, 0.209, 37],
 [0, 86, 68, 32, 0, 35.8, 0.238, 25],
 [6, 183, 94, 0, 0, 40.8, 1.461, 45],
 [4, 171, 72, 0, 0, 43.6, 0.479, 26],
 [4, 137, 84, 0, 0, 31.2, 0.252, 30],
 [10, 68, 106, 23, 49, 35.5, 0.285, 47],
 [6, 154, 74, 32, 193, 29.3, 0.839, 39],
 [4, 83, 86, 19, 0, 29.3, 0.317, 34],
 [1, 97, 70, 40, 0, 38.1, 0.218, 30],
 [8, 100, 76, 0, 0, 38.7, 0.19, 42],
 [1, 136, 74, 50, 204, 37.4, 0.399, 24],
 [2, 110, 74, 29, 125, 32.4, 0.698, 27],
 [1, 97, 64, 19, 82, 18.2, 0.299, 21],
 [4, 95, 60, 32, 0, 35.4, 0.284, 28],
 [4, 92, 80, 0, 0, 42.2, 0.237, 29],
 [3, 139, 54, 0, 0, 25.6, 0.402, 22],
 [1, 103, 30, 38, 83, 43.3, 0.183, 33],
 [7, 181, 84, 21, 192, 35.9, 0.586, 51],
 [0, 94, 70, 27, 115, 43.5, 0.347, 21],
 [1, 124, 74, 36, 0, 27.8, 0.1, 30],
 [2, 129, 84, 0, 0, 28.0, 0.284, 27],
 [3, 113, 50, 10, 85, 29.5, 0.626, 25],
 [1, 103, 80, 11, 82, 19.4, 0.491, 22],
 [1, 164, 82, 43, 67, 32.8, 0.341, 50],
 [3, 111, 58, 31, 44, 29.5, 0.43, 22],
 [7, 97, 76, 32, 91, 40.9, 0.871, 32],
 [0, 152, 82, 39, 272, 41.5, 0.27, 27],
 [4, 111, 72, 47, 207, 37.1, 1.39, 56],
 [4, 115, 72, 0, 0, 28.9, 0.376, 46],
 [0, 114, 80, 34, 285, 44.2, 0.167, 27],
 [2, 99, 52, 15, 94, 24.6, 0.637, 21],
 [4, 110, 92, 0, 0, 37.6, 0.191, 30],
 [1, 95, 66, 13, 38, 19.6, 0.334, 25],
 [2, 128, 64, 42, 0, 40.0, 1.101, 24],
 [8, 108, 70, 0, 0, 30.5, 0.955, 33],
 [0, 126, 86, 27, 120, 27.4, 0.515, 21],
 [0, 137, 70, 38, 0, 33.2, 0.17, 22],
 [3, 99, 80, 11, 64, 19.3, 0.284, 30],
 [8, 183, 64, 0, 0, 23.3, 0.672, 32],
 [2, 88, 58, 26, 16, 28.4, 0.766, 22],
 [9, 112, 82, 32, 175, 34.2, 0.26, 36],
 [8, 143, 66, 0, 0, 34.9, 0.129, 41],
 [1, 128, 98, 41, 58, 32.0, 1.321, 33],
 [3, 173, 84, 33, 474, 35.7, 0.258, 22],
 [7, 161, 86, 0, 0, 30.4, 0.165, 47],
 [2, 108, 62, 10, 278, 25.3, 0.881, 22],
 [1, 193, 50, 16, 375, 25.9, 0.655, 24],
 [1, 111, 86, 19, 0, 30.1, 0.143, 23],
 [11, 120, 80, 37, 150, 42.3, 0.785, 48],
 [4, 112, 78, 40, 0, 39.4, 0.236, 38],
 [5, 103, 108, 37, 0, 39.2, 0.305, 65],
 [3, 115, 66, 39, 140, 38.1, 0.15, 28],
 [12, 121, 78, 17, 0, 26.5, 0.259, 62],
 [1, 143, 74, 22, 61, 26.2, 0.256, 21],
 [2, 90, 60, 0, 0, 23.5, 0.191, 25],
 [4, 127, 88, 11, 155, 34.5, 0.598, 28],
 [5, 116, 74, 29, 0, 32.3, 0.66, 35],
 [1, 135, 54, 0, 0, 26.7, 0.687, 62],
 [2, 175, 88, 0, 0, 22.9, 0.326, 22],
 [5, 139, 64, 35, 140, 28.6, 0.411, 26],
 [7, 105, 0, 0, 0, 0.0, 0.305, 24],
 [2, 81, 60, 22, 0, 27.7, 0.29, 25],
 [1, 172, 68, 49, 579, 42.4, 0.702, 28],
 [7, 94, 64, 25, 79, 33.3, 0.738, 41],
 [9, 102, 76, 37, 0, 32.9, 0.665, 46],
 [1, 107, 50, 19, 0, 28.3, 0.181, 29],
 [7, 103, 66, 32, 0, 39.1, 0.344, 31],
 [3, 141, 0, 0, 0, 30.0, 0.761, 27],
 [2, 120, 54, 0, 0, 26.8, 0.455, 27],
 [2, 87, 58, 16, 52, 32.7, 0.166, 25],
 [4, 154, 72, 29, 126, 31.3, 0.338, 37],
 [1, 105, 58, 0, 0, 24.3, 0.187, 21],
 [7, 62, 78, 0, 0, 32.6, 0.391, 41],
 [7, 114, 66, 0, 0, 32.8, 0.258, 42],
 [1, 99, 58, 10, 0, 25.4, 0.551, 21],
 [5, 88, 66, 21, 23, 24.4, 0.342, 30],
 [6, 80, 66, 30, 0, 26.2, 0.313, 41],
 [1, 97, 68, 21, 0, 27.2, 1.095, 22],
 [2, 105, 80, 45, 191, 33.7, 0.711, 29],
 [4, 85, 58, 22, 49, 27.8, 0.306, 28],
 [4, 142, 86, 0, 0, 44.0, 0.645, 22],
 [3, 116, 74, 15, 105, 26.3, 0.107, 24],
 [1, 107, 72, 30, 82, 30.8, 0.821, 24]]

In [57]:
def yes(today):
    P_Yes_Today=1
    for i in computations0:
        if(i[1]==today[0]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations1:
        if(i[1]==today[1]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations2:
        if(i[1]==today[2]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations3:
        if(i[1]==today[3]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations4:
        if(i[1]==today[4]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations5:
        if(i[1]==today[5]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations6:
        if(i[1]==today[6]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    for i in computations7:
        if(i[1]==today[7]):
            P_Yes_Today=P_Yes_Today*((i[2])/(countY))

    P_Yes_Today=P_Yes_Today*((countY)/len(df))
    return P_Yes_Today

def no(today):
    P_No_Today=1
    for i in computations0:
        if(i[1]==today[0]):
            P_No_Today=P_No_Today*((i[3])/(countN))
        
    for i in computations1:
        if(i[1]==today[1]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations2:
        if(i[1]==today[2]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations3:
        if(i[1]==today[3]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations4:
        if(i[1]==today[4]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations5:
        if(i[1]==today[5]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations6:
        if(i[1]==today[6]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    for i in computations7:
        if(i[1]==today[7]):
            P_No_Today=P_No_Today*((i[3])/(countN))

    P_No_Today=P_No_Today*((countN)/len(df))
    return P_No_Today

In [58]:
output = []
for i in final:
    P_Yes_Today = yes(i)
    P_No_Today = no(i)
    try:
        P_Yes=float(P_Yes_Today)/float(P_Yes_Today+P_No_Today)
        P_No=float(P_No_Today)/float(P_Yes_Today+P_No_Today)
    except:
        P_Yes = 1
        P_No = 0
    if(P_Yes>=P_No):
        output.append(1)
        print("Prediction is 1")
    else:
        output.append(0)
        print("Prediction is 0")

Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 1
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 0
Prediction is 1
Prediction is 0
Prediction is 0

In [59]:
test

,index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,661,1,199,76,43,0,42.9,1.394,22,1
1,122,2,107,74,30,100,33.6,0.404,23,0
2,113,4,76,62,0,0,34.0,0.391,25,0
3,14,5,166,72,19,175,25.8,0.587,51,1
4,529,0,111,65,0,0,24.6,0.660,31,0
...,...,...,...,...,...,...,...,...,...,...
149,476,2,105,80,45,191,33.7,0.711,29,1
150,482,4,85,58,22,49,27.8,0.306,28,0
151,230,4,142,86,0,0,44.0,0.645,22,1
152,527,3,116,74,15,105,26.3,0.107,24,0
153,380,1,107,72,30,82,30.8,0.821,24,0

In [60]:
count = 0
for i in range(len(output)):
    if int(output[i]) == int(test['Outcome'][i]):
        count +=1
print('Accuracy: ',count/len(test))

Accuracy:  0.7142857142857143